export const ROLE = {
  SUPERADMIN: 1,
  BRANCHMANAGER: 2,
  SALESPERSON: 3,
};

const SIGNED_URL_EXPIRY = 60 * 60; // in seconds
const DEFAULT_LIMIT_PER_PAGE = 50;
export { SIGNED_URL_EXPIRY, DEFAULT_LIMIT_PER_PAGE };
